---
name: Build and Test CI

on  :
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - main

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:
    - name: Install cmake
      run: |
        sudo apt-get update && sudo apt-get install cmake

    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install-boost
      with:
        boost_version: 1.81.0 # Minimum tested version
        platform_version: 22.04
        boost_install_dir: /home/runner/latest_boost # Should set this for some reason. Otherwise find_package fails

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configuration
      run: |
        cmake -S ./ -B build -DCMAKE_BUILD_TYPE=Release -DDSVIEW_BUILD_TESTS=ON
      env: 
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Build
      run: |
        cmake --build build

    - name: Testing
      run: |
        cmake --build build --target test
      env:
        CTEST_OUTPUT_ON_FAILURE: ON